Traceback (most recent call last):
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\jpocampo\.conda\envs\nuevo2-env\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Crear un gr√°fico de dispersi√≥n
figx = px.scatter(df_pivot, x='potencia-activa', y='eficiencia-chiller', trendline='ols')

# Actualizar el t√≠tulo y las etiquetas
figx.update_layout(title='Relaci√≥n entre Potencia Activa y Eficiencia Chiller',  xaxis_title='Potencia Activa', yaxis_title='Eficiencia Chiller')

# Mostrar el gr√°fico
figx.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[10], line 2[0m
[0;32m      1[0m [38;5;66;03m# Crear un gr√°fico de dispersi√≥n[39;00m
[1;32m----> 2[0m figx [38;5;241m=[39m px[38;5;241m.[39mscatter([43mdf_pivot[49m, x[38;5;241m=[39m[38;5;124m'[39m[38;5;124mpotencia-activa[39m[38;5;124m'[39m, y[38;5;241m=[39m[38;5;124m'[39m[38;5;124meficiencia-chiller[39m[38;5;124m'[39m, trendline[38;5;241m=[39m[38;5;124m'[39m[38;5;124mols[39m[38;5;124m'[39m)
[0;32m      4[0m [38;5;66;03m# Actualizar el t√≠tulo y las etiquetas[39;00m
[0;32m      5[0m figx[38;5;241m.[39mupdate_layout(title[38;5;241m=[39m[38;5;124m'[39m[38;5;124mRelaci√≥n entre Potencia Activa y Eficiencia Chiller[39m[38;5;124m'[39m,  xaxis_title[38;5;241m=[39m[38;5;124m'[39m[38;5;124mPotencia Activa[39m[38;5;124m'[39m, yaxis_title[38;5;241m=[39m[38;5;124m'[39m[38;5;124mEficiencia Chiller[39m[38;5;124m'[39m)

[1;31mNameError[0m: name 'df_pivot' is not defined
NameError: name 'df_pivot' is not defined

